### PR TITLE
add script for generating redirections

### PR DESCRIPTION
**Pull request by sandro-elsweijer**

### CODE REVIEW

**Comment by sandro-elsweijer** [comment]
Found a bug

**Comment by sandro-elsweijer** [comment]
Fixed the bug

**Comment by holke** [comment]
Is it a good idea to upload the autogenerated files in the repo?

Since t8ddy will generate the files automatically and overwrite it does seem like adding them to the repo only
- introduces file clutter
- leads to the false assumption that the files currently in the repo are the used ones while actually the used ones are always of the newest version.

**Comment by sandro-elsweijer** [comment]
> Is it a good idea to upload the autogenerated files in the repo?
> 
> Since t8ddy will generate the files automatically and overwrite it does seem like adding them to the repo only
> 
>     * introduces file clutter
> 
>     * leads to the false assumption that the files currently in the repo are the used ones while actually the used ones are always of the newest version.

We have to add them now, because t8ddy will only create the new files when a release is triggered.

**Comment by holke** [comment]
> > Is it a good idea to upload the autogenerated files in the repo?
> > Since t8ddy will generate the files automatically and overwrite it does seem like adding them to the repo only
> > ```
> > * introduces file clutter
> > 
> > * leads to the false assumption that the files currently in the repo are the used ones while actually the used ones are always of the newest version.
> > ```
> 
> We have to add them now, because t8ddy will only create the new files when a release is triggered.

So it seems like the best way would be to just trigger a release?
We simply use the same t8code version as is, but increase the patch counter by one.
This would then trigger t8ddy to generate the files once and the we can move forward...

**Comment by sandro-elsweijer** [comment]
Was added with https://github.com/DLR-AMR/t8code-website/pull/69

**Pull request closed without merging**
